pub_hdrs = h{**}

./: $pub_hdrs

# Install into the libtpms/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/libtpms/
  install.subdirs = true
}
